owner: paulfi94 # GitHub username
repo: betterstatus # GitHub repository name
sites: # List of endpoints to track
  - name: Google
    url: https://www.google.com
assignees: # Users to assign downtime issues (optional)
  - AnandChowdhary
status-website:
  baseUrl: /betterstatus # where "repo" is your repository name
  name: Betterbits Status Page
